version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: bomber-redis
    ports:
      - '6379:6379'
    restart: always

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: bomber-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/workspace
    working_dir: /workspace/apps/api
    command: pnpm dev
    depends_on:
      - redis
